import { IoTCard } from "@/lib/types";


export const mockIoTCards: IoTCard[] = [
  {
    id: "flow-temp-001",
    title: "Contrôle température",
    subtitle: "Capteurs chaîne du froid",
    iconType: "thermometer",
    size: 2,
    color: "#1E90FF",
    url: "/flows/temp-control",
    reference: "TMP_FLOW_01",
    readme: "Surveille la température des conteneurs réfrigérés.",
    group: "Industrie",
    stats: {
      paused: false,
      messages: 1280,
      pending: 3,
      memory: 256,
      minutes: 12,
      errors: 0,
      mm: 42,
    },
    createdAt: new Date("2025-05-10T08:15:00Z"),
    errors: false,
    version: "1.3.2",
    // createdBy: "alice",
  },
  {
    id: "flow-stock-002",
    title: "Gestion de stock",
    subtitle: "Niveau de pièces détachées",
    iconType: "box",
    size: 1,
    color: "#E8483F",
    url: "/flows/stock",
    reference: "STOCK_FLOW_01",
    readme: "Met à jour le stock en temps réel (MQTT).",
    group: "Logistique",
    stats: {
      paused: true,
      messages: 540,
      pending: 12,
      memory: 128,
      minutes: 8,
      errors: 1,
      mm: 15,
    },
    createdAt: new Date("2025-04-22T14:30:00Z"),
    errors: true,
    version: "0.9.7",
    createdBy: "bob",
  },
]
