services:
  nats-server:
    image: nats:latest
    container_name: nats-server
    command: -js
    ports:
      - "4222:4222"
    environment:
      - NATS_MAX_PAYLOAD=10MB
  # timescaledb:
  #   image: timescale/timescaledb:latest-pg15
  #   container_name: timescaleDb
  #   ports:
  #     - 5436:5432
  #   environment:
  #     - POSTGRES_PASSWORD=nextronic
  #     - POSTGRES_USER=nextronic
  #     - POSTGRES_DB=nextronic
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=nextronic
      - POSTGRES_USER=nextronic
      - POSTGRES_DB=nextronic
    extra_hosts:
      - "host.docker.internal:host-gateway"
  emqx:
    image: emqx/emqx:5.8.0
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    volumes:
      - ./server/broker/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./server/broker/default_api_key.conf:/opt/emqx/etc/default_api_key.conf
    environment:
      EMQX_NAME: "emqx"
      EMQX_HOST: "localhost"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # node-red:
  #   image: nodered/node-red:latest
  #   ports:
  #     - "1880:1880"
  #   volumes:
  #     - ./nodered/settings.js:/data/settings.js
  #     - ./nodered/logo.png:/data/logo.png

  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  #docker-compose up --build
  #build docker-compose build
  #docker tag service1:latest yourusername/service1:latest
  #docker push tesla11/syncflow_platform:latest
