import type React from "react";
import { createContext, useContext, useEffect, useState } from "react";

type Language = "en" | "fr" | "es" | "ar";

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
  isArabic: boolean;
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Translations for the sidebar and navbar
const translations = {
  en: {
    "nav.dashboard": "Dashboard",
    "nav.device": "Devices",
    "nav.entity": "Entities",
    "nav.connection": "Connection",
    "nav.settings": "Settings",
    "nav.facturation": "Billing",
    "nav.tenant": "Tenants",
    "nav.token": "Tokens",
    "nav.workflow": "Workflows",
    "nav.workflow2": "Workflow2",

    "nav.docs": "Docs",
    "nav.global": "Global",
    "nav.manage": "Manage",
    "nav.profile": "Profile",
    "nav.create": "Create",
    "nav.Users": "Users",
    "nav.brokers": "Brokers",
    "nav.manageFacturation": "Manage Billing",
    "nav.manageTenants": "Manage Tenants",
    "nav.tokens": "Tokens",
    "nav.manageWorkflows": "Manage Workflows",
    "nav.manageWorkflows2": "Manage Workflows2",

    "nav.signOut": "Sign out",
    "nav.language": "Language",
    "nav.english": "English",
    "nav.french": "French",
    "nav.spanish": "Spanish",
    "nav.arabic": "Arabic",
    "device.manageDevices": "Manage Devices",
    "device.addDevice": "Add Device",
    "device.editDevice": "EditDevice",
    "device.newDevice": "Create a new device",
    "device.create": "Create Device",
    "device.selectType": "Select Type",
    "device.selectBroker": "Select Broker",
    "device.Input": "Device Input",
    "device.inputLabel": "Label for input",
    "device.Output": "Device Output",
    "device.outputLabel": "Label for output",
    "device.messages": "Device messages",
    "device.dialog.description":
      "Start by choosing the connectivity type of your device.",

    "entity.manageEntity": "Manage Entity",
    "entity.addEntity": "Add Entity",
    "entity.manageEntityType": "Manage Entity Type",
    "connection.manageConnection": "Manage Connection",
    "connection.addConnection": "Add Connection",
    "connection.newConnection": "Create a new connection",
    "connection.create": "Create Connection",
    "settings.manageUser": "Manage User",
    "token.manageToken": "Manage Token",
    "dashboard.manageDashboard": "Entites Dashboard",
    "dashboard.manageAnalytics": "Analytics Dashboard",
    "dashboard.globalDashboard": "Global Dashboard",
    "dashboard.history": "History",
    "dashboard.downlinks": "Downlinks",
    "dashboard.configuration": "Configuration",
    "dashboard.authorization": "Authorization",
    "nav.analytics": "Analytics",
    "form.close": "Close Form",
    "switcher.title": "Current tenant",
    "switcher.stitle": "Tenants",
    "switcher.search": "Search tenant...",
    "switcher.notfound": "No tenant found.",
    "breadcrumb.home": "Home",
    "breadcrumb.dashboards": "Dashboards",
    "breadcrumb.edit": "Edit",
    "table.column.name": "Name",
    "table.column.serial": "Serial",
    "table.column.actions": "Actions",

    "table.column.broker": "Broker",
    "table.column.deviceInput": "Inputs",
    "table.column.deviceOutput": "Outputs",
    "table.column.status": "Status",
    "table.column.version": "Version",
    "table.column.description": "Description",
    "table.column.createdAt": "Created At",
    "table.column.licence": "Subscription Plan",
    "table.column.admin": "Admin",
    "table.column.email": "Email",
    "table.column.expiryDate": "Expiry Date",
    "table.column.type": "Type",
    "table.column.connected": "Connected",
    "table.column.disconnected": "Disconnected",
    "table.column.device": "Device",
    "table.column.message": "Message",

    "table.filter": "Filter",
    "table.previous": "Previous",
    "table.next": "Next",
    "table.columns": "Columns",
    "table.noResult": "No results",
    "table.rowsSelected": "row(s) selected.",
    "card.navigate": "Navigate",
    "card.info": "Info",
    "card.edit": "Edit",
    "card.delete": "Delete",
    "card.clearDashboard": "Clear Dashboard",

    "broker.title": "Mqtt Brokers",
    "broker.create": "Create Broker",
    "broker.create.title": "Mqtt Connectivity",
    "broker.create.description": "Configure New Mqtt Broker Connection",
    "broker.create.host": "Host Address",
    "broker.create.clientId": "clientId",
    "broker.create.username": "username",
    "broker.create.topic": "Event Topic",
  },
  fr: {
    "broker.title": "Courtiers MQTT",
    "broker.create": "Créer un courtier",
    "broker.create.title": "Connectivité MQTT",
    "broker.create.description":
      "Configurer une nouvelle connexion à un courtier MQTT",
    "broker.create.host": "Adresse de l'hôte",
    "broker.create.clientId": "Identifiant du client",
    "broker.create.username": "Nom d'utilisateur",
    "broker.create.topic": "Sujet de l'événement",

    "nav.dashboard": "Tableau de bord",
    "nav.device": "Appareils",
    "nav.entity": "Entités",
    "nav.connection": "Connexion",
    "nav.settings": "Paramètres",
    "nav.facturation": "Facturation",
    "nav.tenant": "Clients",
    "nav.token": "Jetons",
    "nav.workflow": "Flux de travail",
    "nav.workflow2": "Flux de travail2",

    "nav.docs": "Documentation",
    "nav.global": "Global",
    "nav.manage": "Gérer",
    "nav.profile": "Profil",
    "nav.create": "Créer",
    "nav.Users": "Utilisateurs",
    "nav.brokers": "Courtiers",
    "nav.manageFacturation": "Gérer la facturation",
    "nav.manageTenants": "Gérer les clients",
    "nav.tokens": "Jetons",
    "nav.manageWorkflows": "Gérer les flux de travail",
    "nav.manageWorkflows2": "Gérer les flux de travail2",

    "nav.signOut": "Déconnexion",
    "nav.language": "Langue",
    "nav.english": "Anglais",
    "nav.french": "Français",
    "nav.spanish": "Español",
    "nav.arabic": "Arabe",
    "device.manageDevices": "Gérer les Appareils",
    "device.addDevice": "Ajouter un Appareil",
    "device.editDevice": "Modifier l'appareil",
    "device.newDevice": "Créer un nouvel appareil",
    "device.selectType": "Sélectionner le type",
    "device.selectBroker": "Sélectionner le courtier",
    "device.Input": "Entrée de l'appareil",
    "device.inputLabel": "Étiquette pour l'entrée",
    "device.Output": "Sortie de l'appareil",
    "device.outputLabel": "Étiquette pour la sortie",
    "device.messages": "Messages de l'appareil",
    "device.dialog.description":
      "Commencez par choisir le type de connectivité de votre appareil.",
    "entity.manageEntity": "Gérer l'Entité",
    "entity.addEntity": "Ajouter une Entité",
    "entity.manageEntityType": "Gérer le Type d'Entité",
    "entity.create": "Créer un Type d'Entité",
    "connection.manageConnection": "Gérer la Connexion",
    "connection.addConnection": "Ajouter une Connexion",
    "connection.newConnection": "Créer une nouvelle connexion",
    "connection.create": "Créer une connexion",
    "settings.manageUser": "Gérer l'utilisateur",
    "token.manageToken": "Gérer le jeton",
    "dashboard.manageDashboard": "Tableau de bord des entités",
    "dashboard.manageAnalytics": "Tableau de bord des analyses",
    "dashboard.globalDashboard": "Tableau de bord global",
    "dashboard.history": "Historique",
    "dashboard.downlinks": "Downlinks",
    "dashboard.configuration": "Configuration",
    "dashboard.authorization": "Autorisation",
    "nav.analytics": "Analytique",
    "form.close": "Fermer le formulaire",
    "switcher.title": "Locataire actuel",
    "switcher.stitle": "Locataires",
    "switcher.search": "Rechercher un locataire...",
    "switcher.notfound": "Aucun locataire trouvé.",
    "breadcrumb.home": "Accueil",
    "breadcrumb.dashboards": "Tableaux de bord",
    "breadcrumb.edit": "Modifier",
    "table.column.name": "Nom",
    "table.column.serial": "Numéro de série",
    "table.column.actions": "Actions",
    "table.filter": "Filtrer",
    "table.previous": "Précédent",
    "table.next": "Suivant",
    "table.columns": "Colonnes",
    "table.noResult": "Aucun résultat",
    "table.rowsSelected": "ligne(s) sélectionnée(s).",
    "card.navigate": "Naviguer",
    "card.clearDashboard": "Effacer le tableau de bord",
    "device.create": "Créer un apareil",
    "card.info": "Informations",
    "card.edit": "Modifier",
    "card.delete": "Supprimer",
    "table.column.broker": "Courtier",
    "table.column.deviceInput": "Entrées",
    "table.column.deviceOutput": "Sorties",
    "table.column.status": "Statut",
    "table.column.version": "Version",
    "table.column.description": "Description",
    "table.column.createdAt": "Créé le",
    "table.column.licence": "Plan d'abonnement",
    "table.column.admin": "Administrateur",
    "table.column.email": "E-mail",
    "table.column.expiryDate": "Date d'expiration",
    "table.column.type": "Type",
    "table.column.connected": "Connecté",
    "table.column.disconnected": "Déconnecté",
    "table.column.device": "Appareil",
    "table.column.message": "Message",
  },
  es: {
    "broker.title": "Corredores MQTT",
    "broker.create": "Crear Corredor",
    "broker.create.title": "Conectividad MQTT",
    "broker.create.description":
      "Configurar una nueva conexión de Corredor MQTT",
    "broker.create.host": "Dirección del host",
    "broker.create.clientId": "ID del cliente",
    "broker.create.username": "Nombre de usuario",
    "broker.create.topic": "Tema del evento",
    "nav.dashboard": "Panel",
    "nav.device": "Dispositivos",
    "table.column.device": "Dispositiv",
    "nav.entity": "Entidades",
    "nav.connection": "Conexión",
    "nav.settings": "Ajustes",
    "nav.facturation": "Facturación",
    "nav.tenant": "Inquilinos",
    "nav.token": "Tokens",
    "nav.workflow": "Flujo de trabajo",
    "nav.workflow2": "Flujo de trabajo2",
    "nav.docs": "Documentación",
    "nav.global": "Global",
    "nav.manage": "Gestionar",
    "nav.profile": "Perfil",
    "nav.create": "Crear",
    "nav.Users": "Usuarios",
    "nav.brokers": "Corredores",
    "nav.manageFacturation": "Gestionar facturación",
    "nav.manageTenants": "Gestionar inquilinos",
    "nav.tokens": "Tokens",
    "nav.manageWorkflows": "Gestionar flujos de trabajo",
    "nav.manageWorkflows2": "Gestionar flujos de trabajo2",

    "nav.signOut": "Cerrar sesión",
    "nav.language": "Idioma",
    "nav.english": "Inglés",
    "nav.french": "Francés",
    "nav.spanish": "Español",
    "nav.arabic": "Árabe",
    "device.manageDevices": "Gestionar Dispositivos",
    "device.addDevice": "Añadir Dispositivo",
    "device.newDevice": "Crear un nuevo dispositivo",
    "device.editDevice": "Editar dispositivo",
    "device.create": "Crear dispositivo",
    "device.selectType": "Seleccionar tipo",
    "device.selectBroker": "Seleccionar broker",
    "device.Input": "Entrada del dispositivo",
    "device.inputLabel": "Etiqueta para la entrada",
    "device.Output": "Salida del dispositivo",
    "device.outputLabel": "Etiqueta para la salida",
    "device.dialog.description":
      "Comience eligiendo el tipo de conectividad de su dispositivo.",
    "device.messages": "Mensajes del dispositivo",

    "entity.manageEntity": "Gestionar Entidad",
    "entity.addEntity": "Añadir Entidad",
    "entity.manageEntityType": "Gestionar Tipo de Entidad",
    "entity.create": "Crear Entidad",
    "connection.manageConnection": "Gestionar Conexión",
    "connection.addConnection": "Añadir Conexión",
    "connection.newConnection": "Crear una nueva conexión",
    "connection.create": "Crear conexión",
    "settings.manageUser": "Gestionar usuario",
    "token.manageToken": "Gestionar token",
    "dashboard.manageDashboard": "Panel de control de entidades",
    "dashboard.manageAnalytics": "Panel de control de analíticas",
    "dashboard.globalDashboard": "Panel de control global",
    "dashboard.history": "Historial",
    "dashboard.downlinks": "Downlinks",
    "dashboard.configuration": "Configuración",
    "dashboard.authorization": "Autorización",
    "nav.analytics": "Analítica",
    "form.close": "Cerrar formulario",
    "switcher.title": "Inquilino actual",
    "switcher.stitle": "Inquilinos",
    "switcher.search": "Buscar un inquilino...",
    "switcher.notfound": "No se encontró ningún inquilino.",
    "breadcrumb.home": "Inicio",
    "breadcrumb.dashboards": "Paneles de control",
    "breadcrumb.edit": "Editar",
    "table.column.name": "Nombre",
    "table.column.serial": "Número de serie",
    "table.column.actions": "Acciones",
    "table.column.broker": "Broker",
    "table.column.deviceInput": "Entradas",
    "table.column.deviceOutput": "Salidas",
    "table.column.status": "Estado",
    "table.column.version": "Versión",
    "table.column.description": "Descripción",
    "table.column.createdAt": "Creado el",
    "table.column.licence": "Plan de suscripción",
    "table.column.admin": "Administrador",
    "table.column.email": "Correo electrónico",
    "table.column.expiryDate": "Fecha de vencimiento",
    "table.column.type": "Tipo",
    "table.column.connected": "Conectado",
    "table.column.disconnected": "Desconectado",
    "table.column.message": "Mensaje",
    "table.filter": "Filtrar",
    "table.previous": "Anterior",
    "table.next": "Siguiente",
    "table.columns": "Columnas",
    "table.noResult": "Sin resultados",
    "table.rowsSelected": "fila(s) seleccionada(s).",
    "card.navigate": "Navegar",
    "card.clearDashboard": "Limpiar el panel",
    "card.info": "Información",
    "card.edit": "Editar",
    "card.delete": "Eliminar",
  },
  ar: {
    "broker.title": "وسطاء MQTT",
    "broker.create": "إنشاء وسيط",
    "broker.create.title": "اتصال MQTT",
    "broker.create.description": "تكوين اتصال جديد بوسيط MQTT",
    "broker.create.host": "عنوان المضيف",
    "broker.create.clientId": "معرّف العميل",
    "broker.create.username": "اسم المستخدم",
    "broker.create.topic": "موضوع الحدث",
    "nav.dashboard": "لوحة التحكم",
    "nav.device": "جهاز",
    "table.column.device": "جهاز",
    "nav.entity": "وحدة",
    "nav.connection": "اتصال",
    "nav.settings": "إعدادات",
    "nav.facturation": "الفواتير",
    "nav.tenant": "مستأجر",
    "nav.token": "رمز",
    "nav.workflow": "سير العمل",
    "nav.workflow2": "سير العمل 2",
    "device.create": "إنشاء جهاز",
    "nav.docs": "وثائق",
    "nav.global": "عام",
    "nav.manage": "إدارة",
    "nav.profile": "ملف التعريف",
    "nav.create": "إنشاء",
    "nav.Users": "المستخدمون",
    "nav.brokers": "وسطاء",
    "nav.manageFacturation": "إدارة الفواتير",
    "nav.manageTenants": "إدارة المستأجرين",
    "nav.tokens": "الرموز",
    "nav.manageWorkflows": "إدارة سير العمل",
    "nav.manageWorkflows2": "إدارة سير العمل 2",

    "nav.signOut": "تسجيل الخروج",
    "nav.language": "اللغة",
    "nav.english": "الإنجليزية",
    "nav.french": "الفرنسية",
    "nav.spanish": "الإسبانية",
    "nav.arabic": "العربية",
    "device.manageDevices": "إدارة الأجهزة",
    "device.addDevice": "إضافة جهاز",
    "device.editDevice": "تعديل الجهاز",
    "device.newDevice": "إنشاء جهاز جديد",
    "device.selectType": "اختر النوع",
    "device.selectBroker": "اختر الوسيط",
    "device.Input": "مدخل الجهاز",
    "device.inputLabel": "تسمية للمدخل",
    "device.Output": "مخرج الجهاز",
    "device.outputLabel": "تسمية للمخرج",

    "device.messages": "رسائل الجهاز",
    "device.dialog.description": "ابدأ باختيار نوع الاتصال لجهازك.",
    "entity.manageEntity": "إدارة الوحدة",
    "entity.addEntity": "إضافة الوحدة",
    "entity.manageEntityType": "إدارة الوحدة",
    "connection.manageConnection": "إدارة الاتصال",
    "connection.addConnection": "إضافة اتصال",
    "connection.newConnection": "إنشاء اتصال جديد",
    "connection.create": "إنشاء اتصال",
    "settings.manageUser": "إدارة المستخدم",
    "token.manageToken": "إدارة الرمز",
    "dashboard.manageDashboard": "لوحة تحكم الوحدات",
    "dashboard.manageAnalytics": "لوحة تحكم التحليلات",
    "dashboard.globalDashboard": "لوحة التحكم العامة",
    "nav.analytics": "التحليلات",
    "form.close": "إغلاق استمارة",
    "switcher.title": "المستأجر الحالي",
    "switcher.stitle": "المستأجرون",
    "switcher.search": "البحث عن مستأجر...",
    "switcher.notfound": "لم يتم العثور على مستأجر.",
    "breadcrumb.home": "الرئيسية",
    "breadcrumb.dashboards": "لوحات التحكم",
    "breadcrumb.edit": "تحرير",
    "table.column.name": "الاسم",
    "table.column.serial": "الرقم التسلسلي",
    "table.column.actions": "الإجراءات",
    "table.column.broker": "الوسيط",
    "table.column.deviceInput": "المدخلات",
    "table.column.deviceOutput": "المخرجات",
    "table.column.status": "الحالة",
    "table.column.version": "الإصدار",
    "table.column.description": "الوصف",
    "table.column.createdAt": "تاريخ الإنشاء",
    "table.column.licence": "خطة الاشتراك",
    "table.column.admin": "المسؤول",
    "table.column.email": "البريد الإلكتروني",
    "table.column.expiryDate": "تاريخ الانتهاء",
    "table.column.type": "النوع",
    "table.column.connected": "متصل",
    "table.column.disconnected": "غير متصل",
    "table.column.message": "رسالة",
    "table.filter": "تصفية",
    "table.previous": "السابق",
    "table.next": "التالي",
    "table.columns": "الأعمدة",
    "table.noResult": "لا توجد نتائج",
    "table.rowsSelected": "صف(وف) محدد(ة).",
    "card.navigate": "التنقل",
    "card.clearDashboard": "مسح لوحة التحكم",
    "card.info": "معلومات",
    "card.edit": "تعديل",
    "card.delete": "حذف",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    // Load language from localStorage on initial render
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && ["en", "fr", "es", "ar"].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem("language", newLanguage);
  };

  const t = (key: string): string => {
    return (
      translations[language][
        key as keyof (typeof translations)[typeof language]
      ] || key
    );
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t, isArabic: language === "ar" }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
