name: DEPLOY FRONTEND CI

on:
  workflow_dispatch:
  push:
    branches:
      - "deploy-frontend"
            
env:
  image: digisense-frontend
  org: digieye
  GITOPS_REPO_NAME: factory-platform-gitops
  GITOPS_REPO_OWNER: Edge-MANAGER
  APP_CONFIG_PATH: apps/frontend/manifests 
  VITE_SERVER_URL: https://portail.swerri.com
  VITE_SOCKET_URL: https://portail.swerri.com/ws
  VITE_STRIPE_KEY: pk_test_51N000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

jobs:
  build:
    name: build and push image
    runs-on: ubuntu-latest
    outputs:
      build_tag: ${{steps.build-tag.outputs.BUILD_TAG}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set build tag
        id: build-tag
        shell: bash
        run: |
          echo "BUILD_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: create .env file
        shell: bash
        run: |
          echo "VITE_SERVER_URL=${{ env.VITE_SERVER_URL }}" >> .env
          echo "VITE_SOCKET_URL=${{ env.VITE_SOCKET_URL }}" >> .env
          echo "VITE_STRIPE_KEY=${{ env.VITE_STRIPE_KEY }}" >> .env

      - name: Build docker image
        uses: ./.github/actions/build-docker-image
        with:
          file: ./.dockerfiles/frontend.Dockerfile
          context: ./front
          tags: |
            ${{ env.org }}/${{ env.image }}:${{ env.BUILD_TAG }}
            ${{ env.org }}/${{ env.image }}:latest
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          login: true
          push: true

  update-gitops-repo:
    name: update gitops repo
    needs: build
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
      BUILD_TAG: ${{needs.build.outputs.build_tag}}

    steps:
      - name: Checkout gitops repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITOPS_REPO_OWNER }}/${{ env.GITOPS_REPO_NAME }}
          token: ${{ secrets.PAT }}
          path: ./${{ env.GITOPS_REPO_NAME }}
      - name: Update Image Tag
        shell: sh
        run: |
          cd ./${{ env.GITOPS_REPO_NAME }}/${{ env.APP_CONFIG_PATH }}
          sed 's|image: ${{ env.org }}/${{ env.image }}:.*$|image: ${{ env.org }}/${{ env.image }}:${{ env.BUILD_TAG }}|' -i ./install.yml
          cat  ./install.yml

      - name: Push changes
        uses: EndBug/add-and-commit@v7
        with:
          cwd: ./${{ env.GITOPS_REPO_NAME }}
          message: "Update [${{ env.APP_CONFIG_PATH }}] from ${{ github.REPOSITORY }} | ${{ env.BUILD_TAG }}"
          branch: HEAD 